In [1]:
import sys
import os 
import numpy as np
import pandas as pd
from pulp import *

sys.path.append(os.path.abspath("../../"))
from types import SimpleNamespace
from optimizer.configuration import load_active_runtime
settings = SimpleNamespace(**load_active_runtime())
# sys.path.insert(0, os.path.abspath("../../../../Generic-Parallel-Compute-Helper/")); from parallel_compute import *
from functools import partial
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm

from optimizer.optimizer_visualizer import create_window_progress_visual, update_window_progress_visual
from optimizer.optimizer_inputs import prepare_optimizer_inputs, select_optimization_case

pd.set_option('display.max_rows', None) ; pd.set_option('display.max_columns', None)

### Post optimization calculation logic

In [2]:
# Called for every window
def post_process_window_logic(self):
    
    def compute_interval_assumed_revenue():
    
        interval_assumed_revenue = [0.0] * len(self.dataset_window_subset)
        interval_demand_charges = [0.0] * len(self.dataset_window_subset)
        stored_charge = [value(v) for v in self.stored_charge]
        date = [v for v in self.dataset_window_subset['Date']]

        for component_name, interval_exprs in self.objective_component_map.items():
            for i, expr in interval_exprs.items():
                if i is not None and 0 <= i < len(self.dataset_window_subset):

                    component_value = value(expr)
                    if component_name == "monthly_import_export_penalties":
                        interval_demand_charges[i] += component_value
                        if settings.optimize_with_duos:
                            interval_assumed_revenue[i] += component_value
                    else:
                        interval_assumed_revenue[i] += component_value
        
        # interval_assumed_revenue = interval_assumed_revenue + np.array(window_demand_charges)
                  
        return interval_assumed_revenue, interval_demand_charges, stored_charge, date
    

    def compute_interval_actual_revenue(window_demand_charges):

        n = len(self.dataset_window_subset)
        actual_price = self.dataset_window_subset["Actual_price"].to_numpy() * settings.price_escalation_factor
        lgc = self.dataset_window_subset["LGC"].to_numpy()
        import_charge = self.dataset_window_subset["Import_charge"].to_numpy()
        hte2grid = self.dataset_window_subset["hte2grid"].to_numpy()
        generation = self.dataset_window_subset["Generation"].to_numpy()

        pv2grid_v = np.array([value(v) or 0.0 for v in self.pv2grid[:n]])
        pv2battery_v = np.array([value(v) or 0.0 for v in self.pv2battery[:n]])
        dischargeE_v = np.array([value(v) or 0.0 for v in self.dischargeE[:n]])
        grid2battery_v = np.array([value(v) or 0.0 for v in self.grid2battery[:n]])
        dischargeE_eff = dischargeE_v * hte2grid

        energy_revenue = (
            (pv2grid_v * settings.tlf_pv_injection + dischargeE_eff * settings.tlf_bess_injection) * actual_price
            - grid2battery_v * (actual_price * settings.tlf_bess_withdrawal + import_charge)
        )
        if settings.lgc_eligibility_basis == "Generation":
            lgc_eligible_volume = generation
        elif settings.lgc_eligibility_basis == "Renewable dispatched":
            lgc_eligible_volume = pv2grid_v + pv2battery_v
        elif settings.lgc_eligibility_basis == "Net export":
            lgc_eligible_volume = pv2grid_v + dischargeE_eff - grid2battery_v * settings.grid_import_penalty
        else:
            lgc_eligible_volume = (pv2grid_v + dischargeE_eff - grid2battery_v * settings.grid_import_penalty) * settings.tlf_pv_injection
        lgc_revenue = lgc_eligible_volume * lgc
        revenue_expression = energy_revenue + lgc_revenue

        duos_in_objective = np.array(window_demand_charges) if settings.optimize_with_duos else 0.0
        return revenue_expression + duos_in_objective, energy_revenue, lgc_revenue, pv2grid_v, pv2battery_v, grid2battery_v, dischargeE_eff
    
    interval_assumed_revenue, interval_demand_charges, interval_stored_charge, interval_date = compute_interval_assumed_revenue()
    interval_actual_revenue, interval_energy_revenue, interval_lgc_revenue, interval_pv2grid, interval_pv2battery, interval_grid2battery, interval_discharge_to_grid = compute_interval_actual_revenue(interval_demand_charges)
    

    optimization_interval_results = pd.DataFrame({
            "interval_date":interval_date,
            "interval_stored_charge": interval_stored_charge,
            "interval_assumed_revenue": interval_assumed_revenue,
            "interval_actual_revenue": interval_actual_revenue,
            "interval_energy_revenue": interval_energy_revenue,
            "interval_lgc_revenue": interval_lgc_revenue,
            "interval_duos_charges": -np.array(interval_demand_charges),
            "interval_pv2grid": interval_pv2grid,
            "interval_pv2battery": interval_pv2battery,
            "interval_grid2battery": interval_grid2battery,
            "interval_discharge_to_grid": interval_discharge_to_grid,
            "interval_grid_exports": interval_pv2grid + interval_discharge_to_grid,
            "interval_tou_label": self.dataset_window_subset["ToU_label"].to_numpy(),
        })
    
    
    return optimization_interval_results

### Export logic

In [3]:
# Only called once at the end
def export_outut_to_csv(retained_outputs, price_col_indexer, bess_duration_h):

    retained_outputs = retained_outputs.copy()
    retained_outputs["interval_date"] = pd.to_datetime(retained_outputs["interval_date"])

    output = {
        "price_col_indexer": price_col_indexer,
        "bess_duration_h": bess_duration_h,
    }

    annual_revenue = (
        retained_outputs.groupby(retained_outputs["interval_date"].dt.year)[
            ["interval_assumed_revenue", "interval_actual_revenue", "interval_energy_revenue", "interval_lgc_revenue", "interval_duos_charges"]
        ]
        .sum()
        .round(0)
    )

    for year, row in annual_revenue.iterrows():
        output[f"assumed_revenue_{year}"] = row["interval_assumed_revenue"]
        output[f"actual_revenue_{year}"] = row["interval_actual_revenue"]
        output[f"energy_revenue_{year}"] = row["interval_energy_revenue"]
        output[f"lgc_revenue_{year}"] = row["interval_lgc_revenue"]
        output[f"duos_charges_{year}"] = row["interval_duos_charges"]
        output[f"gross_merchant_revenue_{year}"] = row["interval_energy_revenue"] + row["interval_lgc_revenue"]
        output[f"net_merchant_revenue_{year}"] = row["interval_energy_revenue"] + row["interval_lgc_revenue"] - row["interval_duos_charges"]

    return pd.DataFrame([output])

## Constraints:

#### Ballance PV output

In [4]:
def _interval_constraint_A(Lp, gen, pv2grid, pv2battery, curtailment, i):
    
    Lp += pv2grid + pv2battery + curtailment == gen, f"Ballance_PV_output_{i}"
    
    return Lp

#### Ballance BESS charge

In [5]:
def _interval_constraint_B(Lp, pv2battery_eff, grid2battery_eff, dischargeE, previous_interval_mwh, stored_charge,i):
   
    Lp += previous_interval_mwh + (pv2battery_eff + grid2battery_eff) - dischargeE == stored_charge, f"Ballance_BESS_charge_{i}"
    
    return Lp

#### Restrict BESS by BESS capacity

In [6]:
def _interval_constraint_C(Lp, pv2battery_eff, grid2battery_eff, dischargeE_eff, bess_energy_limit_per_interval_mw,i):

    Lp += pv2battery_eff + grid2battery_eff + dischargeE_eff <= bess_energy_limit_per_interval_mw, f"Restrict_BESS_by_BESS_capacity_{i}"

    return Lp

#### Restrict BESS by BESS physical limits

In [7]:
def _interval_constraint_D(Lp, stored_charge, bess_max_eff, chargeE, dischargeE, gen_exportable_now, pv2battery, gen_exportable,i):

    Lp += stored_charge <= bess_max_eff, f"Restrict_stored_charge_by_physcial_limit_{i}"

    Lp += chargeE <= bess_max_eff, f"Restrict_chargeE_by_physcial_limit_{i}"

    Lp += dischargeE <= bess_max_eff, f"Restrict_dischargeE_by_physcial_limit_{i}"

    # if gen_exportable_now == True:
    #     Lp += pv2battery <= gen_exportable
            
    return Lp

#### Restrict grid by grid capacity

In [8]:
def _interval_constraint_E(Lp, pv2grid, dischargeE_eff, project_poi_export_limit_mwh_per_interval, grid2battery, project_poi_import_limit_mwh_per_interval,i):

  
    Lp += pv2grid + dischargeE_eff <= project_poi_export_limit_mwh_per_interval, f"Restrict_grid_exports_by_grid_capacity_{i}"

    Lp += grid2battery <= project_poi_import_limit_mwh_per_interval, f"Restrict_grid_imports_by_grid_capacity_{i}"
    
    return Lp

#### Restrict BESS by signal mutuality

In [9]:
def _interval_constraint_F(Lp, charge_signal, discharge_signal, chargeE, dischargeE,i):

    if charge_signal == True:
        Lp += dischargeE == 0, f"Restrict_BESS_by_dischargeE_mutuality_{i}"
    
    if discharge_signal == True:
        Lp += chargeE == 0, f"Restrict_BESS_by_chargeE_mutuality_{i}"

    return Lp

#### Restrict grid importing during sun soaker times

In [10]:
def _interval_constraint_G(Lp, sun_soaker, grid2battery,i):
    
    if sun_soaker == True:
        Lp += grid2battery == 0,f"Restrict_importing_by_sunsoaker_{i}"
    
    return Lp

#### Restrict imports and exports to be equal or less than max monthly values

In [11]:
def _interval_constraint_H(Lp, tou_label, grid2battery, imports_max_peak, imports_max_shoulder, imports_max_offpeak, exports_max_sunsoaker, dischargeE_eff, pv2grid,i): 

        if tou_label == "Peak":
            Lp += grid2battery <= imports_max_peak, f"Restrict_onpeak_grid_imports_by_max_{i}"

        elif tou_label == "Shoulder":
            Lp += grid2battery <= imports_max_shoulder, f"Restrict_shoulder_grid_imports_by_max_{i}"

        elif tou_label == "Off-peak":
            Lp += grid2battery <= imports_max_offpeak, f"Restrict_peak_grid_imports_by_max_{i}"

        elif tou_label == "Sun Soaker":
            Lp += pv2grid + dischargeE_eff <= exports_max_sunsoaker, f"Restrict_sunsoaker_grid_exports_by_max_{i}"

        return Lp

#### Restrict BESS by cycle limit

In [12]:
def _window_constraint_A(Lp, window_cycle_budget, total_window_cycles):

    Lp += total_window_cycles <= window_cycle_budget, f"Restrict_BESS_by_cycle_limit"

    return Lp

## Panalties:

#### Penalise revenue by, price of, remaining BESS headroom, upon charge signal

In [13]:
def _interval_penalty_A(bess_capacity_remaining, charge_signal, trade_signal_penalty):
    
    if charge_signal:
        charge_signal_penalty = bess_capacity_remaining * trade_signal_penalty
        
        return charge_signal_penalty

#### Penalise revenue by, price of, remaining BESS stored charge, upon discharge signal

In [14]:
def _interval_penalty_B(discharge_signal, trade_signal_penalty, stored_charge):
   
    if discharge_signal:
        discharge_signal_penalty = stored_charge * trade_signal_penalty

        return discharge_signal_penalty

#### Penalise revenue by, price of, curtailed energy

In [15]:
def _interval_penalty_C(curtailment, curtailment_penalty):
    curtailed_energy_penalty = curtailment * curtailment_penalty
    
    return curtailed_energy_penalty

#### Penalise revenue by, import/export tarrifs

In [16]:
def _monthly_penalty_A(import_charge_peak, import_charge_shoulder, import_charge_off_peak, export_charge_sun_soaker, grid2battery_max_peak, grid2battery_max_shoulder, grid2battery_max_offpeak, export_max):
        
    interval_energy_to_mw = 60 / settings.operation_granularity_in_minutes
    demand_penalty = interval_energy_to_mw * ((import_charge_peak * grid2battery_max_peak) + (import_charge_shoulder * grid2battery_max_shoulder) + (import_charge_off_peak * grid2battery_max_offpeak) + (export_charge_sun_soaker * export_max))
    
    return demand_penalty

## Objective expression - interval level:

#### Each interval builds one symbolic revenue expression; the final objective sums them once.

In [17]:
def _interval_expression(price, lgc_price, lgc_eligible_volume, grid2battery, pv2grid, dischargeE_eff, import_charge, charge_signal, discharge_signal, charge_signal_penalty, discharge_signal_penalty, curtailed_energy_penalty):

    objective_components = {
        "exporting_energy_revenue": (pv2grid * settings.tlf_pv_injection + dischargeE_eff * settings.tlf_bess_injection) * price,
        "lgc_revenue": lgc_eligible_volume * lgc_price,
        "importing_energy_cost": -(grid2battery * (price * settings.tlf_bess_withdrawal + import_charge)),
        "curtailed_energy_penalty": -curtailed_energy_penalty,
        "charge_signal_penalty": -charge_signal_penalty if charge_signal else 0,
        "discharge_signal_penalty": -discharge_signal_penalty if discharge_signal else 0,
    }

    interval_expression = lpSum(objective_components.values())

    return interval_expression, objective_components

## Objective expression - window level:

In [18]:
def _objective(self):
    
    duos_penalty = lpSum(self.monthly_import_export_penalties) if settings.optimize_with_duos else 0
    self.Lp += lpSum(self.interval_objective_expressions) - duos_penalty, "Total_window_revenue"

    return self.Lp

## Within-window optimisation design logic:

### Interval level logic

In [19]:
def _interval_level_logic(self, i):

    # Dataset, quick reference
    generation = self.dataset_window_subset['Generation'].iloc[i]

    # Default signal and penalty values; overridden below when using BESS instructions
    charge_signal = False
    discharge_signal = False
    charge_signal_penalty = 0
    discharge_signal_penalty = 0

    predicted_price = self.dataset_window_subset["Predicted_price"].iloc[i] * settings.price_escalation_factor
    
    if settings.prediction_signal_transform == 2:
      
        # BESS instruction only
        if settings.predicted_price_type == 2:
            predicted_price = 0.0
            charge_signal = (self.dataset_window_subset["BESS_instruction"][i]) == 1
            discharge_signal = (self.dataset_window_subset["BESS_instruction"][i]) == 2

        # Both
        elif settings.predicted_price_type == 3:
            charge_signal = (self.dataset_window_subset["BESS_instruction"][i]) == 1
            discharge_signal = (self.dataset_window_subset["BESS_instruction"][i]) == 2

    lgc_price = self.dataset_window_subset["LGC"].iloc[i]
    import_charge = self.dataset_window_subset["Import_charge"][i]
    tou_label = self.dataset_window_subset["ToU_label"].iloc[i]
    gen_exportable = self.dataset_window_subset['Generation_exportable'][i]
    
    # Decision variables, quick reference
    pv2grid = self.pv2grid[i]
    pv2battery = self.pv2battery[i]
    curtailment = self.curtailment[i]
    grid2battery = self.grid2battery[i]
    dischargeE = self.dischargeE[i]
    stored_charge = self.stored_charge[i]

    year_month = self.window_year_month[i] 
    
    # Other calculated varibles, quick reference
    chargeE = self.pv2battery[i] + self.grid2battery[i]
    pv2battery_eff = pv2battery * self.dataset_window_subset["hte_from_pv"].iloc[i]
    grid2battery_eff = grid2battery * self.dataset_window_subset["hte_from_grid"].iloc[i]
    dischargeE_eff = dischargeE * self.dataset_window_subset["hte2grid"].iloc[i]

    def _previous_interval():
        previous_window_ending_mwh = self.window_start_soc * self.bess_mwh
        previous_interval_mwh = previous_window_ending_mwh if i == 0 else self.stored_charge[i - 1]
        return previous_interval_mwh
    
    previous_interval_mwh = _previous_interval()

    bess_max_eff = self.bess_mwh * self.dataset_window_subset["bess_deg"].iloc[i]
    bess_capacity_remaining = bess_max_eff - self.stored_charge[i]

    gen_exportable_now = self.dataset_window_subset['Generation_exportable'][i] > 0
    sun_soaker = self.dataset_window_subset["ToU_label"].iloc[i] != "Sun Soaker"

    
    # Call constraints
    self.Lp = _interval_constraint_A(self.Lp, generation, pv2grid, pv2battery, curtailment, i)
    self.constraint_map[f"Ballance_PV_output_{i}"] = i

    self.Lp = _interval_constraint_B(self.Lp, pv2battery_eff, grid2battery_eff, dischargeE, previous_interval_mwh, stored_charge, i)
    self.constraint_map[f"Ballance_BESS_charge_{i}"] = i

    self.Lp = _interval_constraint_C(self.Lp, pv2battery_eff, grid2battery_eff, dischargeE_eff, self.bess_energy_limit_per_interval_mw, i)
    self.constraint_map[f"Restrict_BESS_by_BESS_capacity_{i}"] = i
    
    self.Lp = _interval_constraint_D(self.Lp, stored_charge, bess_max_eff, chargeE, dischargeE, gen_exportable_now, pv2battery, gen_exportable, i)
    self.constraint_map[f"Restrict_stored_charge_by_physcial_limit_{i}"] = i
    self.constraint_map[f"Restrict_chargeE_by_physcial_limit_{i}"] = i
    self.constraint_map[f"Restrict_dischargeE_by_physcial_limit_{i}"] = i

    self.Lp = _interval_constraint_E(self.Lp, pv2grid, dischargeE_eff, settings.project_poi_export_limit_mwh_per_interval, grid2battery, settings.project_poi_import_limit_mwh_per_interval, i)
    self.constraint_map[f"Restrict_grid_by_grid_capacity_{i}"] = i

    if settings.prediction_signal_transform == 2 and settings.predicted_price_type != 1:
        self.Lp = _interval_constraint_F(self.Lp, charge_signal, discharge_signal, chargeE, dischargeE, i)
        self.constraint_map[f"Restrict_BESS_by_dischargeE_mutuality_{i}"] = i
        self.constraint_map[f"Restrict_BESS_by_chargeE_mutuality_{i}"] = i

    # self.Lp = _interval_constraint_G(self.Lp, sun_soaker, grid2battery, i)
    # self.constraint_map[f"Restrict_importing_by_sunsoaker_{i}"] = i

    if i < self.retained_interval_count:
        self.Lp = _interval_constraint_H(self.Lp, tou_label, grid2battery, self.imports_max_peak[year_month], self.imports_max_shoulder[year_month], self.imports_max_offpeak[year_month], self.exports_max_sunsoaker[year_month], dischargeE_eff, pv2grid, i)
        self.constraint_map[f"Restrict_monthly_grid_max_{i}"] = i

    # Call penalties
    if settings.prediction_signal_transform == 2 and settings.predicted_price_type != 1:
        charge_signal_penalty = _interval_penalty_A(bess_capacity_remaining, charge_signal, settings.trade_signal_penalty)
        discharge_signal_penalty = _interval_penalty_B(discharge_signal, settings.trade_signal_penalty, stored_charge)

    curtailed_energy_penalty = _interval_penalty_C(curtailment, settings.curtailment_penalty)

    if settings.lgc_eligibility_basis == "Generation":
        lgc_eligible_volume = generation
    elif settings.lgc_eligibility_basis == "Renewable dispatched":
        lgc_eligible_volume = pv2grid + pv2battery
    elif settings.lgc_eligibility_basis == "Net export":
        lgc_eligible_volume = pv2grid + dischargeE_eff - grid2battery * settings.grid_import_penalty
    else:
        lgc_eligible_volume = (pv2grid + dischargeE_eff - grid2battery * settings.grid_import_penalty) * settings.tlf_pv_injection

    # Call objective expression
    interval_expression, interval_objective_components = _interval_expression(predicted_price, lgc_price, lgc_eligible_volume, grid2battery, pv2grid, dischargeE_eff, import_charge, charge_signal, discharge_signal, charge_signal_penalty, discharge_signal_penalty, curtailed_energy_penalty)
    for component_name, component_expr in interval_objective_components.items():
        self.objective_component_map.setdefault(component_name, {})[i] = component_expr
    self.interval_objective_expressions.append(interval_expression)

    return self

### Window level logic

In [20]:
def _window_level_logic(self):
    total_window_cycles = lpSum([self.dischargeE[i] / (self.bess_mwh * self.dataset_window_subset["bess_deg"].iloc[i]) for i in self.dataset_index_range])
    self.Lp = _window_constraint_A(self.Lp, self.window_cycle_budget, total_window_cycles)

    return self

### Within-window controller

In [21]:
class Optimizer():

    def __init__(self, dataset_window_subset:pd.DataFrame, window_start_soc:float, dataset_index_range:range, bess_mwh, bess_energy_limit_per_interval_mw, retained_interval_count:int, monthly_peak_state:dict):
        self.dataset_window_subset = dataset_window_subset
        self.window_start_soc = window_start_soc
        self.dataset_index_range = dataset_index_range
        self.interval_objective_expressions = []
        self.monthly_import_export_penalties = []
        self.objective_component_map = {}
        self.constraint_map = {}
        self.retained_interval_count = retained_interval_count
        self.monthly_peak_state = monthly_peak_state

        self.bess_mwh = bess_mwh
        self.bess_energy_limit_per_interval_mw = bess_energy_limit_per_interval_mw

        self.window_months, self.window_year_month = self._calculate_years_months()
        self.window_cycle_budget = self._calculate_cycle_budget()
        self._main_loop()
    

    def _calculate_years_months(self):
        window_dates = pd.to_datetime(self.dataset_window_subset["Date"])
        window_year_month = list(zip(window_dates.dt.year.to_numpy(), window_dates.dt.month.to_numpy()))
        window_months = sorted(set(window_year_month[:self.retained_interval_count]))
        return window_months, window_year_month
        
    def _calculate_cycle_budget(self):
        periods_per_day = 24 * (60 / settings.operation_granularity_in_minutes)
        days_in_window = len(self.dataset_window_subset) / periods_per_day
        return settings.cycles_per_day * days_in_window
    
    def _main_loop(self):
        # Define Linear Programming optimization type
        self.Lp = LpProblem("Optimization", LpMaximize)
        
        # Define decision variables
        self.stored_charge = [LpVariable(f"stored_charge_{i}", lowBound=0) for i in self.dataset_index_range]
        self.pv2grid = [LpVariable(f"pv2grid_{i}", lowBound=0) for i in self.dataset_index_range]
        self.pv2battery = [LpVariable(f"pv2battery_{i}", lowBound=0) for i in self.dataset_index_range]
        self.curtailment = [LpVariable(f"curtailment_{i}", lowBound=0) for i in self.dataset_index_range]
        self.dischargeE = [LpVariable(f"dischargeE_{i}", lowBound=0) for i in self.dataset_index_range]
        self.grid2battery = [LpVariable(f"grid2battery_{i}", lowBound=0, upBound=settings.project_poi_import_limit_mwh_per_interval,) for i in self.dataset_index_range]
        previous_peak = lambda ym, kind: float(self.monthly_peak_state.get((ym, kind), 0.0))
        self.imports_max_peak = {ym: LpVariable(f"imports_max_peak_{ym[0]}_{ym[1]:02d}", lowBound=previous_peak(ym, "Peak")) for ym in self.window_months}
        self.imports_max_shoulder = {ym: LpVariable(f"imports_max_shoulder_{ym[0]}_{ym[1]:02d}", lowBound=previous_peak(ym, "Shoulder")) for ym in self.window_months}
        self.imports_max_offpeak = {ym: LpVariable(f"imports_max_offpeak_{ym[0]}_{ym[1]:02d}", lowBound=previous_peak(ym, "Off-peak")) for ym in self.window_months}
        self.exports_max_sunsoaker = {ym: LpVariable(f"exports_max_sunsoaker_{ym[0]}_{ym[1]:02d}", lowBound=previous_peak(ym, "Sun Soaker")) for ym in self.window_months}
     
        # Create per month objective penalties here
        for ym in self.window_months:

            total_monthly_penalty = _monthly_penalty_A(settings.demand_charge_peak,settings.demand_charge_shoulder,settings.demand_charge_off_peak,settings.export_charge_sun_soaker,self.imports_max_peak[ym],self.imports_max_shoulder[ym],self.imports_max_offpeak[ym],self.exports_max_sunsoaker[ym])
            previous_monthly_penalty = _monthly_penalty_A(settings.demand_charge_peak,settings.demand_charge_shoulder,settings.demand_charge_off_peak,settings.export_charge_sun_soaker,previous_peak(ym, "Peak"),previous_peak(ym, "Shoulder"),previous_peak(ym, "Off-peak"),previous_peak(ym, "Sun Soaker"))
            monthly_import_export_penalty = total_monthly_penalty - previous_monthly_penalty
            self.monthly_import_export_penalties.append(monthly_import_export_penalty)
            first_interval_of_month = self.window_year_month.index(ym)
            self.objective_component_map.setdefault("monthly_import_export_penalties", {})[first_interval_of_month] = -monthly_import_export_penalty

        # Create per INTERVAL constraints and objectives
        for i in self.dataset_index_range:
            _interval_level_logic(self, i)

        # Create per WINDOW constraints and objectives
        _window_level_logic(self)

        # Create objective
        self.Lp = _objective(self)

        # Solve
        self.model = self.Lp.solve(PULP_CBC_CMD(msg=0))

## Window scheduler logic:

In [22]:
def create_optimisation(inputs, item=None):

    dataset, bess_mwh, bess_energy_limit_per_interval_mw, scenario_label, bess_row = select_optimization_case(inputs, item)


    length_of_single_lookahead_window = int(int(settings.optimization_avoid_edge_effect_total_hours) * (60 / int(settings.operation_granularity_in_minutes)))
    length_of_window_minus_lookahead = int(int(settings.number_of_intervals_per_window) - length_of_single_lookahead_window)

    retained_outputs = []
    monthly_peak_state = {}
    window_start_soc = settings.start_soc
    window_interval_stride = length_of_window_minus_lookahead

    if settings.display_window_scheduler_visual and not settings.run_multiple_optimisations:
        # Visualisation purposes only
        window_starts = list(range(0, len(dataset), window_interval_stride))
        intervals_per_bar = length_of_single_lookahead_window
        if intervals_per_bar <= 0:
            intervals_per_bar = max(1, int(24 * 60 / settings.operation_granularity_in_minutes))
        bars_per_window = int(settings.number_of_intervals_per_window / intervals_per_bar)
        retained_bars_per_window = int(length_of_window_minus_lookahead / intervals_per_bar)
        fig, completed_x, completed_y, completed_colors = create_window_progress_visual(
            window_starts=window_starts,
            total_dataset_intervals=len(dataset),
            intervals_per_bar=intervals_per_bar,
            bars_per_window=bars_per_window,
            retained_bars_per_window=retained_bars_per_window,
            dataset=dataset,
        )
        
    for i, start_interval in enumerate(range(0, len(dataset), window_interval_stride)):

        stop_interval = min(start_interval + settings.number_of_intervals_per_window, len(dataset))
        dataset_window_subset = dataset.iloc[start_interval:stop_interval].copy().reset_index(drop=True)
        dataset_index_range = range(len(dataset_window_subset))
        retained_interval_count = len(dataset_window_subset) if stop_interval == len(dataset) else min(length_of_window_minus_lookahead, len(dataset_window_subset))
        
        Optimization = Optimizer(dataset_window_subset=dataset_window_subset, window_start_soc=window_start_soc, dataset_index_range=dataset_index_range, bess_mwh=bess_mwh, bess_energy_limit_per_interval_mw=bess_energy_limit_per_interval_mw, retained_interval_count=retained_interval_count, monthly_peak_state=monthly_peak_state)

        optimization_output = post_process_window_logic(Optimization)
        
        optimization_output["Window"] = i

        if stop_interval == len(dataset):
            retained_optimization_output = optimization_output
        else:
            retained_optimization_output = optimization_output.iloc[:length_of_window_minus_lookahead].copy()
            last_retained_stored_charge_mwh = optimization_output["interval_stored_charge"].iloc[length_of_window_minus_lookahead - 1]
            window_start_soc = last_retained_stored_charge_mwh / bess_mwh

        retained_dates = pd.to_datetime(retained_optimization_output["interval_date"])
        retained_year_month = list(zip(retained_dates.dt.year, retained_dates.dt.month))
        for ym in sorted(set(retained_year_month)):
            month_mask = np.array([value == ym for value in retained_year_month])
            month_output = retained_optimization_output.loc[month_mask]
            for tou in ("Peak", "Shoulder", "Off-peak"):
                values = month_output.loc[month_output["interval_tou_label"] == tou, "interval_grid2battery"]
                if not values.empty:
                    monthly_peak_state[(ym, tou)] = max(monthly_peak_state.get((ym, tou), 0.0), float(values.max()))
            values = month_output.loc[month_output["interval_tou_label"] == "Sun Soaker", "interval_grid_exports"]
            if not values.empty:
                monthly_peak_state[(ym, "Sun Soaker")] = max(monthly_peak_state.get((ym, "Sun Soaker"), 0.0), float(values.max()))

        retained_outputs.append(retained_optimization_output)

        if settings.display_window_scheduler_visual and not settings.run_multiple_optimisations:
            # Visualisation purposes only
            actual_bars_this_window = min(bars_per_window, int((stop_interval - start_interval) / intervals_per_bar))
            if actual_bars_this_window > 0:
                update_window_progress_visual(fig=fig, current_window=i, current_horizon_bar=actual_bars_this_window - 1, window_starts=window_starts, bars_per_window=bars_per_window, completed_x=completed_x, completed_y=completed_y, completed_colors=completed_colors, force=(stop_interval == len(dataset)))

    retained_outputs = pd.concat(retained_outputs, ignore_index=True, sort=False)
    retained_outputs = retained_outputs.round(4)
    
    # Call the export function
    export_df = export_outut_to_csv(retained_outputs, scenario_label, bess_row["BESS_Duration_h"])

    return export_df

## Prepare optimization inputs (Code entry point)

In [23]:
inputs = prepare_optimizer_inputs()
dataset = inputs["dataset"]

In [24]:
dataset.head()

,Date,LGC,Import_charge,ToU_label,bess_deg,hte_from_pv,hte_from_grid,hte2grid,pv_bess_grid,grid_bess_grid
0,2025-01-01 00:00:00,17.400849,0.0,Off-peak,1.007194,0.952314,0.878956,0.920296,0.841979,0.808900
1,2025-01-01 00:30:00,17.400849,0.0,Off-peak,1.007192,0.952313,0.878955,0.920296,0.841979,0.808900
2,2025-01-01 01:00:00,17.400849,0.0,Off-peak,1.007190,0.952313,0.878955,0.920296,0.841978,0.808899
3,2025-01-01 01:30:00,17.400849,0.0,Off-peak,1.007189,0.952313,0.878955,0.920296,0.841978,0.808899
4,2025-01-01 02:00:00,17.400849,0.0,Off-peak,1.007187,0.952312,0.878954,0.920296,0.841978,0.808898

In [25]:
inputs["price_actual"].head()

                 Date  Scenario 1
0 2025-01-01 00:00:00  142.139393
1 2025-01-01 00:30:00  128.254977
2 2025-01-01 01:00:00  120.268893
3 2025-01-01 01:30:00  112.776788
4 2025-01-01 02:00:00  110.633045

In [26]:
inputs["price_predicted"].head()

                 Date  Scenario 1
0 2025-01-01 00:00:00  142.139393
1 2025-01-01 00:30:00  128.254977
2 2025-01-01 01:00:00  120.268893
3 2025-01-01 01:30:00  112.776788
4 2025-01-01 02:00:00  110.633045

In [27]:
inputs["bess_sizes"].head()

   BESS_Duration_h  BESS_Power_MW     BESS_MWh  BESS_MWh_per_interval
0              4.0          400.0  1738.570182                  200.0

## Singular / parrallel coordinator

In [28]:
# single series operating mode
if settings.run_multiple_optimisations == False:
    results = create_optimisation(inputs)
    display(results)

# multi series operating mode
if settings.run_multiple_optimisations == True:

    def create_dataset_combinations():
        return inputs["items"]
    
    if settings.execution_mode == "sequential":   
        function = partial(create_optimisation, inputs)

        results = []

        for item in tqdm(create_dataset_combinations()):
            results.append(function(item))

        results = pd.concat(results, ignore_index=True)

    if settings.execution_mode == "parallel":

        function = partial(create_optimisation, inputs)
        with ThreadPoolExecutor() as executor:
            results = pd.concat(list(executor.map(function, create_dataset_combinations())), ignore_index=True)


results.to_csv("Optimization_data/optimization_results.csv", index=False)

C:\Users\Daniel\AppData\Local\Temp\ipykernel_19716\3960503617.py:73: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  retained_outputs = retained_outputs.round(4)

,price_col_indexer,bess_duration_h,assumed_revenue_2025,actual_revenue_2025,energy_revenue_2025,lgc_revenue_2025,duos_charges_2025,gross_merchant_revenue_2025,net_merchant_revenue_2025
0,price=Scenario 1|generation=Scenario 1|bess=0,4.0,174354101.0,174354101.0,161699495.0,12654606.0,83422016.0,174354101.0,90932085.0